// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5NtGwNcLaou1n0MHxrbalmPGAE4feHeQ',
    appId: '1:102757205218:web:e4eb8622c3d6f760d2cabb',
    messagingSenderId: '102757205218',
    projectId: 'avariasrota',
    authDomain: 'avariasrota.firebaseapp.com',
    storageBucket: 'avariasrota.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3FFvfQ4pslXaIv7MqCpv2yQrizPc0SYg',
    appId: '1:102757205218:android:872dd54195547b86d2cabb',
    messagingSenderId: '102757205218',
    projectId: 'avariasrota',
    storageBucket: 'avariasrota.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-aBlbv32e7L6u2zsSLDI6zOoK6VRYqSQ',
    appId: '1:102757205218:ios:d2dc5c7599a0adf2d2cabb',
    messagingSenderId: '102757205218',
    projectId: 'avariasrota',
    storageBucket: 'avariasrota.appspot.com',
    iosBundleId: 'com.example.meuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-aBlbv32e7L6u2zsSLDI6zOoK6VRYqSQ',
    appId: '1:102757205218:ios:8cd56f82ec92affcd2cabb',
    messagingSenderId: '102757205218',
    projectId: 'avariasrota',
    storageBucket: 'avariasrota.appspot.com',
    iosBundleId: 'com.example.meuapp.RunnerTests',
  );
}
